# -*- coding: utf-8 -*-
"""Dish names as the data stores them, with an English description for
image-text models.

CLIP-style models (SigLIP2 included) were trained mostly on English captions,
so a photo is compared against "a photo of pho (noodle soup)", not against
"Phở". The keys are the restaurant tags exactly as they appear in the data,
so a match maps straight back to a searchable tag. Kept in step with
Frontend/app/lib/dishesEn.ts, which is where the descriptions were written.
"""

DISH_PROMPTS: dict[str, str] = {
    "Hải sản": "Seafood",
    "Lẩu": "Hot pot",
    "Lẩu mắm": "Fermented-fish hot pot",
    "Ốc": "Snails & shellfish",
    "Ốc hút": "Sucking snails",
    "Kem": "Ice cream",
    "Chè": "Che (sweet soup)",
    "Tào phớ": "Tofu pudding",
    "Cà phê": "Coffee",
    "Trà sữa": "Bubble tea",
    "Trà": "Tea",
    "Sinh tố": "Smoothies",
    "Nước ép": "Fresh juice",
    "Dừa": "Coconut",
    "Phở": "Pho (noodle soup)",
    "Phở Bắc": "Northern-style pho",
    "Phở bò": "Beef pho",
    "Phở gà": "Chicken pho",
    "Phở cuốn": "Pho rolls",
    "Bún": "Rice vermicelli",
    "Bún bò Huế": "Bun bo Hue (spicy beef noodle soup)",
    "Bún đậu mắm tôm": "Bun dau (tofu, noodles & shrimp paste)",
    "Bún chả": "Bun cha (grilled pork & noodles)",
    "Bún chả cá": "Fish cake noodle soup",
    "Bún cá": "Fish noodle soup",
    "Bún mắm": "Fermented-fish noodle soup",
    "Bún riêu": "Crab noodle soup",
    "Bún thịt nướng": "Grilled pork vermicelli",
    "Bún ốc": "Snail noodle soup",
    "Bún thang": "Bun thang (Hanoi chicken & egg noodle soup)",
    "Bún mọc": "Pork meatball noodle soup",
    "Bún nước lèo": "Khmer fish noodle soup",
    "Bún dọc mùng": "Noodle soup with taro stems",
    "Mì Quảng": "Mi Quang (turmeric noodles)",
    "Mì": "Egg noodles",
    "Mì trộn": "Dry mixed noodles",
    "Miến": "Glass noodles",
    "Miến lươn": "Eel glass-noodle soup",
    "Miến trộn": "Dry glass noodles",
    "Hủ tiếu": "Hu tieu (clear noodle soup)",
    "Hủ tiếu Nam Vang": "Phnom Penh-style noodle soup",
    "Hủ tiếu Mỹ Tho": "My Tho-style noodle soup",
    "Bánh canh": "Banh canh (thick noodle soup)",
    "Bánh canh cá lóc": "Snakehead fish thick noodle soup",
    "Bánh canh chả cá": "Fish cake thick noodle soup",
    "Bánh đa": "Flat rice noodles",
    "Bánh đa cua": "Crab flat-noodle soup",
    "Cao lầu": "Cao lau (Hoi An noodles)",
    "Súp": "Soup",
    "Cơm": "Rice dishes",
    "Cơm tấm": "Com tam (broken rice)",
    "Cơm tấm Long Xuyên": "Long Xuyen broken rice",
    "Cơm gà": "Chicken rice",
    "Cơm gà Hội An": "Hoi An chicken rice",
    "Cơm gà xối mỡ": "Crispy fried chicken rice",
    "Cơm niêu": "Clay-pot rice",
    "Cơm chiên": "Fried rice",
    "Cơm hến": "Hue clam rice",
    "Xôi": "Sticky rice",
    "Cháo": "Rice porridge",
    "Cháo lòng": "Pork offal porridge",
    "Cháo vịt": "Duck porridge",
    "Cháo lươn": "Eel porridge",
    "Bánh mì": "Banh mi (sandwich)",
    "Bánh bao": "Steamed buns",
    "Bánh xèo": "Banh xeo (sizzling pancake)",
    "Bánh xèo tôm nhảy": "Shrimp sizzling pancake",
    "Bánh khọt": "Mini shrimp pancakes",
    "Bánh căn": "Banh can (mini rice cakes)",
    "Bánh cuốn": "Banh cuon (steamed rice rolls)",
    "Bánh ướt": "Steamed rice sheets",
    "Bánh bèo": "Steamed rice cakes",
    "Bánh bột lọc": "Tapioca dumplings",
    "Bánh nậm": "Flat rice dumplings",
    "Bánh hỏi": "Woven rice noodles",
    "Bánh đúc": "Rice cake",
    "Bánh tằm": "Silkworm-shaped rice noodles",
    "Bánh tráng": "Rice paper",
    "Bánh tráng trộn": "Rice paper salad",
    "Bánh tráng nướng": "Grilled rice paper",
    "Bánh tráng kẹp": "Folded grilled rice paper",
    "Bánh tráng thịt heo": "Pork & rice paper rolls",
    "Bột chiên": "Fried rice-flour cake",
    "Gỏi cuốn": "Fresh spring rolls",
    "Gỏi": "Vietnamese salad",
    "Gỏi khô bò": "Dried beef salad",
    "Ram": "Crispy rolls",
    "Chả": "Pork sausage",
    "Chả cá": "Fish cake",
    "Chả lụi": "Grilled skewers",
    "Nem": "Nem (spring rolls)",
    "Nem nướng": "Grilled pork sausage",
    "Nem nướng Nha Trang": "Nha Trang grilled pork rolls",
    "Nem chua rán": "Fried fermented pork",
    "Nem lụi": "Lemongrass pork skewers",
    "Nem cua": "Crab spring rolls",
    "Gà": "Chicken",
    "Vịt": "Duck",
    "Dê": "Goat",
    "Bò": "Beef",
    "Bò kho": "Beef stew",
    "Bò lá lốt": "Beef in betel leaves",
    "Bò né": "Sizzling beef & eggs",
    "Lươn": "Eel",
    "Lòng": "Offal",
    "Thịt quay": "Roast pork",
    "Chân gà": "Chicken feet",
    "Cá viên chiên": "Fried fish balls",
}

# What a restaurant's cover photo often is instead of food. Used to tell a
# usable dish photo from a logo, a menu board or a promotional banner.
NON_FOOD_PROMPTS: dict[str, str] = {
    "logo": "a brand logo on a plain colored background",
    "menu": "a restaurant menu or price list with lots of text",
    "banner": "a promotional banner or poster with large text",
    "storefront": "the outside of a shop or restaurant",
    "people": "a photo of people",
}
